before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    main: ./cmd/send-cleanup
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.buildDate={{.CommitDate}}"
    ignore:
      - goos: darwin
        goarch: "386"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
